name: Mobile Tests

on:
  push:
    branches: [ main ]

jobs:
  android-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Appium
        run: |
          npm install -g appium@2
          appium driver install uiautomator2@2.29.2

      - name: Instalar Python e Robot
        run: |
          pip install robotframework
          pip install robotframework-appiumlibrary

      - name: Baixar APK
        run: |
          mkdir -p app
          wget https://github.com/saucelabs/sample-app-mobile/releases/download/2.7.1/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk -O app/app.apk

      - name: Rodar emulator e testes
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: pixel
          script: |
            appium &
            robot tests/